# Generated by Django 3.2.9 on 2021-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0012_alter_profile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('swimmers', models.ManyToManyField(to='ranker.Profile')),
            ],
        ),
    ]
