# Generated by Django 3.2.9 on 2021-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0013_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='swimmers',
            field=models.ManyToManyField(blank=True, to='ranker.Profile'),
        ),
    ]
