# Generated by Django 3.2.9 on 2021-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0016_remove_entry_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
