# Generated by Django 3.2.9 on 2021-12-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0017_auto_20211205_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
