# Generated by Django 3.2.9 on 2021-11-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0003_auto_20211125_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
