# Generated by Django 3.2.9 on 2021-11-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0004_entry_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sex',
            field=models.CharField(default='MALE', max_length=5),
            preserve_default=False,
        ),
    ]
